<?php

declare(strict_types=1);
namespace AfiuCMS\Controllers\Admin;
use AfiuCMS\Core\AuditLogger;use AfiuCMS\Core\Auth;use AfiuCMS\Core\Database;use AfiuCMS\Core\Flash;use AfiuCMS\Core\Gate;use AfiuCMS\Core\Http\Request;use AfiuCMS\Core\Http\Response;use AfiuCMS\Core\Settings;use AfiuCMS\Core\View;
final class MenuController extends AdminController{
 public function __construct(View $v,Auth $a,Settings $s,private readonly Database $db,private readonly Gate $gate,private readonly AuditLogger $audit){parent::__construct($v,$a,$s);} private function allowed():bool{return $this->gate->role()==='administrator';}
 public function index(Request $r):Response{if(!$this->allowed())return $this->forbidden();$menus=$this->db->all('SELECT * FROM menus ORDER BY name');$selected=(int)$r->query('menu',0);if($selected<1&&$menus)$selected=(int)$menus[0]['id'];$items=$selected?$this->db->all('SELECT * FROM menu_items WHERE menu_id=? ORDER BY sort_order,id',[$selected]):[];$pages=$this->db->all("SELECT title,slug FROM content WHERE type='page' AND status='published' ORDER BY title");return $this->page('admin.menus.index',compact('menus','selected','items','pages'));}
 public function storeMenu(Request $r):Response{if(!$this->allowed())return $this->forbidden();$name=trim((string)$r->input('name'));if($name===''){Flash::put('error','Menu name is required.');return Response::redirect('/admin/menus');}$location=(string)$r->input('location','');$location=in_array($location,['primary','footer'],true)?$location:null;try{$this->db->execute('INSERT INTO menus (name,location) VALUES (?,?)',[mb_substr($name,0,120),$location]);$id=$this->db->insertId();$this->audit->record('menu.created','menu',$id,['name'=>$name]);Flash::put('success','Menu created.');return Response::redirect('/admin/menus?menu='.$id);}catch(\Throwable){Flash::put('error','That menu location is already assigned.');return Response::redirect('/admin/menus');}}
 public function addItem(Request $r,string $id):Response{if(!$this->allowed())return $this->forbidden();$menu=(int)$id;$label=trim((string)$r->input('label'));$url=trim((string)$r->input('url'));if($label===''||$url===''){Flash::put('error','Menu label and URL are required.');return Response::redirect('/admin/menus?menu='.$menu);}if(!str_starts_with($url,'/')&&!preg_match('#^https?://#i',$url))$url='/'.ltrim($url,'/');$target=$r->input('target')==='_blank'?'_blank':'_self';$sort=(int)$r->input('sort_order',0);$this->db->execute('INSERT INTO menu_items (menu_id,label,url,target,sort_order) VALUES (?,?,?,?,?)',[$menu,mb_substr($label,0,150),mb_substr($url,0,500),$target,$sort]);$this->audit->record('menu_item.created','menu',$menu,['label'=>$label]);Flash::put('success','Menu item added.');return Response::redirect('/admin/menus?menu='.$menu);}
 public function deleteItem(string $id):Response{if(!$this->allowed())return $this->forbidden();$item=$this->db->one('SELECT * FROM menu_items WHERE id=?',[(int)$id]);if($item){$this->db->execute('DELETE FROM menu_items WHERE id=?',[(int)$id]);$this->audit->record('menu_item.deleted','menu_item',(int)$id);}Flash::put('success','Menu item removed.');return Response::redirect('/admin/menus?menu='.(int)($item['menu_id']??0));}
}
