<?php

declare(strict_types=1);
namespace AfiuCMS\Controllers\Admin;
use AfiuCMS\Core\AuditLogger;use AfiuCMS\Core\Auth;use AfiuCMS\Core\Database;use AfiuCMS\Core\Flash;use AfiuCMS\Core\Gate;use AfiuCMS\Core\Http\Request;use AfiuCMS\Core\Http\Response;use AfiuCMS\Core\Settings;use AfiuCMS\Core\Slugger;use AfiuCMS\Core\View;
final class TaxonomyController extends AdminController{
 public function __construct(View $v,Auth $a,Settings $s,private readonly Database $db,private readonly Gate $gate,private readonly AuditLogger $audit){parent::__construct($v,$a,$s);} public function categories():Response{return $this->index('category');} public function tags():Response{return $this->index('tag');}
 public function storeCategory(Request $r):Response{return $this->store($r,'category');} public function storeTag(Request $r):Response{return $this->store($r,'tag');} public function deleteCategory(string $id):Response{return $this->delete((int)$id,'category');} public function deleteTag(string $id):Response{return $this->delete((int)$id,'tag');}
 private function index(string $type):Response{if(!$this->gate->allows('taxonomy.manage'))return $this->forbidden();$items=$this->db->all('SELECT t.*,COUNT(ct.content_id) usage_count FROM taxonomies t LEFT JOIN content_taxonomy ct ON ct.taxonomy_id=t.id WHERE t.type=? GROUP BY t.id ORDER BY t.name',[$type]);return $this->page('admin.taxonomies.index',compact('items','type'));}
 private function store(Request $r,string $type):Response{if(!$this->gate->allows('taxonomy.manage'))return $this->forbidden();$name=trim((string)$r->input('name'));$slug=Slugger::make(trim((string)$r->input('slug'))?:$name);if($name===''||$slug===''){Flash::put('error','Name is required.');return Response::redirect('/admin/'.($type==='category'?'categories':'tags'));}try{$this->db->execute('INSERT INTO taxonomies (type,name,slug,description) VALUES (?,?,?,?)',[$type,mb_substr($name,0,120),$slug,trim((string)$r->input('description'))]);$id=$this->db->insertId();$this->audit->record('taxonomy.created',$type,$id,['name'=>$name]);Flash::put('success',ucfirst($type).' created.');}catch(\Throwable){Flash::put('error','A '.$type.' with this slug already exists.');}return Response::redirect('/admin/'.($type==='category'?'categories':'tags'));}
 private function delete(int $id,string $type):Response{if(!$this->gate->allows('taxonomy.manage'))return $this->forbidden();$this->db->execute('DELETE FROM taxonomies WHERE id=? AND type=?',[$id,$type]);$this->audit->record('taxonomy.deleted',$type,$id);Flash::put('success',ucfirst($type).' deleted.');return Response::redirect('/admin/'.($type==='category'?'categories':'tags'));}
}
